import argparse
parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest="operation", required=True)
base_op_parser = argparse.ArgumentParser(add_help=False)
base_op_parser.add_argument("--backend", type=str, required=True)
base_op_parser.add_argument("--local_dir", type=str, required=True)
base_op_parser.add_argument("--hf_model_path", type=str, default=None)
merge_parser = subparsers.add_parser("merge", parents=[base_op_parser])
merge_parser.add_argument("--target_dir", default="tmp", type=str)
merge_parser.add_argument("--hf_upload_path", default=None, type=str)
args = parser.parse_args()
print("hf_model_path:", args.hf_model_path)
print("hf_upload_path:", args.hf_upload_path)
print("target_dir:", args.target_dir)
